import { NavigationContainer, DefaultTheme } from "@react-navigation/native";
const LightTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    background: "white",
    backgroundWhite: "#FFFFFF",
    text: "#202020",
    secendory: "#5F8B7A",
    secendory1: "rgba(95, 139, 122, 0.1)",
    primary: "#283629",
    gradientCol: "#608D79",
    gradientCol2: "rgba(96, 141, 121, 0)",
    textBlack: "#202020",
    textBlack2: "#404040",
    textBlack3: "#0D0D12",
    textWhite: "#FFFFFF",
    shadowCol: "#000000",
    greyCol: "#F6F6F6",
    textGreen: "#283629",
    backgroundGreen: "#D5E1DC",
    borderCol: "#F0F0F0",
    firstButtonColor: "rgba(95, 139, 122, 0.2)",
    secondButtonColor: "rgba(95, 139, 122, 1)",
    profileBorder: "#5F8B7ACC",
    greyCol2: "#F5F5F5",
    borderBlu: "#00C2FF",
    textGrey: "#B5B5B5",
    notificationTitle: "#150000",
    chatBackground: "#5F8B7A26",
    chatContainer: "#5F8B7A4D",
    backgroundCol2:"#FBFBFB",
    backgroundCol3: "#EFF3F2",
    redCol: "#FF4A4A",

  },
  images: {
    logo: require("../assets/applogo.png"),
    onboardingImg1: require("../assets/onboard1.png"),
    onboardingImg2: require("../assets/onboard2.png"),
    onboardingImg3: require("../assets/onboard3.png"),
    bg: require("../assets/bg.jpg"),
    downArrow: require("../assets/icons/downarrow.png"),
    googleIcon: require("../assets/icons/googleIcon.png"),
    checkTikIcon: require("../assets/icons/checktik.png"),
    // appleIcon: require("../assets/icons/appleicon.png"),
    lineIcon: require("../assets/icons/Line.png"),
    uploadIcon: require("../assets/icons/upload.png"),
    cameraIcon: require("../assets/icons/camera.png"),
    imageIcon: require("../assets/icons/image.png"),
    closeIcon: require("../assets/icons/close.png"),
    addIcon: require("../assets/icons/add.png"),
    backCircleIcon: require("../assets/icons/backcircle.png"),
    tikCircleIcon: require("../assets/icons/tikcircle.png"),
    kingIcon: require("../assets/icons/king.png"),
    dash: require("../assets/dashboard.png"),
    tree: require("../assets/tree.png"),
    chat: require("../assets/chat.png"),
    profile: require("../assets/profile.png"),
    checked: require("../assets/check.png"),
    unchecked: require("../assets/unchecked.png"),
    arrow: require("../assets/arrowright.png"),
    toggleon: require("../assets/toggleon.png"),
    toggleoff: require("../assets/toggleoff.png"),
    userprofile: require("../assets/userprofile.png"),
    editicon: require("../assets/editicon.png"),
    cameraIcon1: require("../assets/icons/camera1.png"),
    videoIcon: require("../assets/icons/video.png"),
    searchIcon: require("../assets/icons/search.png"),
    locationIcon: require("../assets/icons/location.png"),
    profileIcon: require("../assets/icons/profile.png"),
    johnIcon: require("../assets/icons/john.png"),
    jonuIcon: require("../assets/icons/jonu.png"),
    jennyIcon: require("../assets/icons/jenny.png"),
    jenny2Icon: require("../assets/icons/jenny2.png"),
    heartIcon: require("../assets/icons/heart.png"),
    heartRedIcon: require("../assets/icons/heartred.png"),
    pageIcon: require("../assets/icons/page.png"),
    commentIcon: require("../assets/icons/comment.png"),
    shareIcon: require("../assets/icons/share.png"),
    fileIcon: require("../assets/icons/file.png"),
    upArrowIcon: require("../assets/icons/uparrow.png"),
<<<<<<< HEAD
    delete: require("../assets/delete.png"),
    userimg: require("../assets/usrimg.png"),
    threedot: require("../assets/dot.png"),
    attach: require("../assets/icons/attach.png"),
    send: require("../assets/icons/send.png"),
    group1: require("../assets/group1.png"),
    group2: require("../assets/group2.png"),
    group3: require("../assets/group3.png"),
    group4: require("../assets/group4.png"),
    loading: require("../assets/icons/loading.png"),

=======
>>>>>>> 3e1b5a7228b32842295118d68c248b41ef0ef783
    deleteIcon: require("../assets/icons/delete.png"),
    removeIcon: require("../assets/icons/remove.png"),
    okIcon: require("../assets/icons/ok.png"),
    bellIcon: require("../assets/icons/belli.png"),
    addMoreIcon: require("../assets/icons/addmore.png"),
    rightArrow: require("../assets/icons/rightarrow.png"),
    eyeIcon: require("../assets/icons/eye.png"),
    babyIcon: require("../assets/icons/baby.png"),
<<<<<<< HEAD
    apple: require("../assets/appl.png"),
=======
    galleryIcon: require("../assets/icons/gallery.png"),
    logoutIcon: require("../assets/icons/logout.png"),
    baby2Icon: require("../assets/icons/baby2.png"),
    motherIcon: require("../assets/icons/mother.png"),
    bigIcon: require("../assets/icons/big.png"),
    smallPicIcon: require("../assets/icons/smallpic.png"),
>>>>>>> 3e1b5a7228b32842295118d68c248b41ef0ef783

  },
};

const DarkTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    background: "#FFFFFF",
    backgroundWhite: "#FFFFFF",
    text: "#202020",
    secendory: "#5F8B7A",
    secendory1: "rgba(95, 139, 122, 0.1)",
    primary: "#283629",
    textBlack: "#202020",
    textWhite: "#FFFFFF",
    gradientCol: "#608D79",
    shadowCol: "#000000",
    textBlack2: "#404040",
    textBlack3: "#0D0D12",
    greyCol: "#F6F6F6",
    textGreen: "#283629",
    backgroundGreen: "#D5E1DC",
    borderCol: "#F0F0F0",
    firstButtonColor: "rgba(95, 139, 122, 0.2)",
    secondButtonColor: "rgba(95, 139, 122, 1)",
    profileBorder: "#5F8B7ACC",
    greyCol2: "#F5F5F5",
    borderBlu: "#00C2FF",
    textGrey: "#B5B5B5",
    notificationTitle: "#150000",
    chatBackground: "#5F8B7A26",
    chatContainer: "#5F8B7A4D",
    backgroundCol2:"#FBFBFB",
    backgroundCol3: "#EFF3F2",
    redCol: "#FF4A4A",
  },
  images: {
    logo: require("../assets/applogo.png"),
    onboardingImg1: require("../assets/onboard1.png"),
    onboardingImg2: require("../assets/onboard2.png"),
    onboardingImg3: require("../assets/onboard3.png"),
    bg: require("../assets/bg.jpg"),
    downArrow: require("../assets/icons/downarrow.png"),
    googleIcon: require("../assets/icons/googleIcon.png"),
    checkTikIcon: require("../assets/icons/checktik.png"),
    // appleIcon: require("../assets/icons/appleicon.png"),
    lineIcon: require("../assets/icons/Line.png"),
    uploadIcon: require("../assets/icons/upload.png"),
    cameraIcon: require("../assets/icons/camera.png"),
    imageIcon: require("../assets/icons/image.png"),
    closeIcon: require("../assets/icons/close.png"),
    addIcon: require("../assets/icons/add.png"),
    backCircleIcon: require("../assets/icons/backcircle.png"),
    tikCircleIcon: require("../assets/icons/tikcircle.png"),
    kingIcon: require("../assets/icons/king.png"),
    dash: require("../assets/dashboard.png"),
    tree: require("../assets/tree.png"),
    chat: require("../assets/chat.png"),
    profile: require("../assets/profile.png"),
    checked: require("../assets/check.png"),
    unchecked: require("../assets/unchecked.png"),
    arrow: require("../assets/arrowright.png"),
    toggleon: require("../assets/toggleon.png"),
    toggleoff: require("../assets/toggleoff.png"),
    userprofile: require("../assets/userprofile.png"),
    editicon: require("../assets/editicon.png"),
    cameraIcon1: require("../assets/icons/camera1.png"),
    videoIcon: require("../assets/icons/video.png"),
    searchIcon: require("../assets/icons/search.png"),
    locationIcon: require("../assets/icons/location.png"),
    profileIcon: require("../assets/icons/profile.png"),
    johnIcon: require("../assets/icons/john.png"),
    jonuIcon: require("../assets/icons/jonu.png"),
    jennyIcon: require("../assets/icons/jenny.png"),
    jenny2Icon: require("../assets/icons/jenny2.png"),
    heartIcon: require("../assets/icons/heart.png"),
    heartRedIcon: require("../assets/icons/heartred.png"),
    pageIcon: require("../assets/icons/page.png"),
    commentIcon: require("../assets/icons/comment.png"),
    shareIcon: require("../assets/icons/share.png"),
    fileIcon: require("../assets/icons/file.png"),
<<<<<<< HEAD
    delete: require("../assets/delete.png"),
    userimg: require("../assets/usrimg.png"),
    threedot: require("../assets/dot.png"),
    attach: require("../assets/icons/attach.png"),
    send: require("../assets/icons/send.png"),
    group1: require("../assets/group1.png"),
    group2: require("../assets/group2.png"),
    group3: require("../assets/group3.png"),
    group4: require("../assets/group4.png"),
    loading: require("../assets/icons/loading.png"),
=======

>>>>>>> 3e1b5a7228b32842295118d68c248b41ef0ef783
    deleteIcon: require("../assets/icons/delete.png"),
    removeIcon: require("../assets/icons/remove.png"),
    okIcon: require("../assets/icons/ok.png"),
    bellIcon: require("../assets/icons/belli.png"),
    addMoreIcon: require("../assets/icons/addmore.png"),
    rightArrow: require("../assets/icons/rightarrow.png"),
    eyeIcon: require("../assets/icons/eye.png"),
    babyIcon: require("../assets/icons/baby.png"),
<<<<<<< HEAD
    apple: require("../assets/appl.png"),
=======
   galleryIcon: require("../assets/icons/gallery.png"),
   logoutIcon: require("../assets/icons/logout.png"),
   baby2Icon: require("../assets/icons/baby2.png"),
   motherIcon: require("../assets/icons/mother.png"),
   bigIcon: require("../assets/icons/big.png"),
   smallPicIcon: require("../assets/icons/smallpic.png"),

>>>>>>> 3e1b5a7228b32842295118d68c248b41ef0ef783

  },
};
export { LightTheme, DarkTheme };
